### ISSUE TITLE
Ways of registering interest in a topic?

### ISSUE THREAD

**Issue by lfilho** [lfilho/new-project-submission#1]
How would the best way of registering interest in a topic be?

**Comment by lfilho** [comment]
# Idea 1

**Actor**: the dev interested in a topic/project.

* Topic is not listed on `master` and there's no PR for that yet :arrow_right: Create PR submitting the topic and adding himself as interested.
* Topic is not listed on `master` but a PR is already open for that :arrow_right: Subscribe for notifications on that PR until it gets merged. Then:
* Topic is already listed on  `master` :arrow_right: Submit PR adding yourself as also interested.

**Comment by joshwnj** [comment]
I like this approach. 

Q. how easy is it to get a list of people who are subscribed to a PR?

**Comment by lfilho** [comment]
Uhm... Not easy it seems.

Seems like it's only possible to GET the watchers for a REPO, not subscribers to specific issue or PR:
https://developer.github.com/v3/activity/watching
https://developer.github.com/v3/activity/notifications
https://developer.github.com/v3/pulls/

**Comment by joshwnj** [comment]
We could for example use the https://developer.github.com/v3/issues/comments/ API to get a list of everyone who replied with `:+1:`

**Comment by lfilho** [comment]
Sounds good. But what if we get false positives? I mean, what if someone
says `:+1:` just to express he/she supports that proposal or that he/she
likes this project... ?

Maybe PRing his/her name into a waitlist is more reliable?

**Comment by joshwnj** [comment]
Good point. I think we'll probably get more insight into this as we move forward with it. 

So for now, we have 2 options:

A. adding `:+1` to the thread (simpler user experience, chance of false-positive)
B. submitting a PR (more complicated user experience, more reliable)

Remembering that it's usually easier to add complexity as needed, than it is to take it away, I would probably be happier going with option A and accepting the occasional false-positive.  I have a feeling that in those cases it will be an easy resolution anyway (ie. just choose someone else if the candidate turns out to be not interested after all).

**Comment by lfilho** [comment]
That's the true essence of being agile right there. Let's us go with A. then :)
